### ISSUE TITLE
Typo in kwargs in print_convergencehistory

### ISSUE THREAD

**Issue by jpthiele** [WIAS-PDELib/ExtendableFEM.jl#17]
The keyword argument `seperated` should be separated.
I am not sure how much this is used and I can look into ways to deprecate such an argument.

Since we are still on 0.x we could also 'simply' rename this and hope no-one is using it so far.

**Comment by j-fu** [comment]
Just as a remark: at this point, Julia extends the notion of semver: Julia Pkg considers a change from 0.n to 0.n+1 as breaking.

BTW that is why I nowadays think that makes sense to move to versions 1.x as early as possible.

**Comment by chmerdon** [comment]
I think nobody else is using this particular function, so I would not mind to simply rename it at this stage. 

Before releasing 1.0 I think we should think about refactoring some bulky parts of the code like the FEEvaluator as @jpthiele and @pjaap already suggested earlier.

**Comment by pjaap** [comment]
fixed by #18
